name: Snake Animation Generator
on:
  schedule:
    - cron: "0 0 * * *"  # Daily updates at midnight UTC
  workflow_dispatch:     # Manual trigger option

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Snake Graphic
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: snake.svg  # Required
          # gif_out_path: snake.gif  # Uncomment if you want GIF version
          # theme: dark  # Optional: light/dark/gradient

      - name: Upload Snake Artifact
        uses: actions/upload-artifact@v3
        with:
          name: snake-animation
          path: snake.svg

      - name: Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: output
          keep_files: false
