name: Snake Animation Updater

on:
  schedule:
    - cron: "0 0 * * *"  # Daily updates
  workflow_dispatch:     # Manual trigger

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: ./snake.svg
          gif_out_path: ./snake.gif  # Optional
          theme: dark  # Options: light/dark/gradient
          
      - name: Deploy to Output Branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output
          folder: .
          clean: true
          single-commit: true
